name: 'Build CA/Browser Forum Guideline'
description: 'Convert a Pandoc-flavored Markdown file to PDF and DOCX using the CA/B Forum Guideline template'
inputs:
  markdown_file:
    description: 'Name of the file to convert'
    required: true
  diff_file:
    description: 'Previous version to diff against (EXPERIMENTAL)'
    required: false
    default: ''
  pdf:
    description: 'Generate a PDF file (true/false)'
    required: false
    default: 'true'
  docx:
    description: 'Generate a DOCX (true/false)'
    required: false
    default: 'true'
  lint:
    description: 'Check for broken self-reference links (true/false)'
    required: false
    default: 'false'
  draft:
    description: 'Include a draft watermark (PDF-only for now) (true/false)'
    required: false
    default: 'false'
outputs:
  pdf_file:
    description: 'The generated PDF file (if pdf was true), relative to GITHUB_WORKSPACE'
  docx_file:
    description: 'The generated DOCX file (if docx was true), relative to GITHUB_WORKSPACE'
  pdf_redline_file:
    description: 'The generated PDF redline file (if pdf was true and diff_file was supplied), relative to GITHUB_WORKSPACE'
  file_version:
    description: 'The version of the file, as extracted from the subtitle of the document'
  diff_version:
    description: 'The version of the diff file, as extracted from the subtitle of the document'
  changelog:
    description: 'A list of commit messages from diff commit to file commit.'
runs:
  using: 'docker'
  image: 'Dockerfile'
